[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_treasury = "AAJL4DeXnWBNRowWjvpkAgwtAACpz6NfaA1T2p8Hrpy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/riolis/.config/solana/id.json"

[scripts]
deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/utils/calls/deposit.ts"
withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/utils/calls/withdraw.ts"
withdraw-owner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/utils/calls/withdraw-owner.ts"
getaddress = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/utils/get-address.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.ts"
